blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', cache_page(60)(BlogListView.as_view()), name='blog'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('users.urls', namespace='users')),
                  path('client/', include('clients.urls', namespace='clients')),
                  path('distribution/', include('distribution.urls', namespace='distribution')),
                  path('blog', include('blog.urls', namespace='blog')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from config import settings

NULLABLE = {'blank': True, 'null': True}


class Post(models.Model):
    ACTIVE_CHOICES = ((True, 'Активна'), (False, 'На модерации'))

    title = models.CharField(max_length=100, verbose_name='Заголовок')
    slug = models.CharField(max_length=100, **NULLABLE, verbose_name='Slug')
    description = models.TextField(**NULLABLE, verbose_name='Содержимое')
    image = models.ImageField(upload_to='blog/', **NULLABLE, verbose_name='Изображение(превью)')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, choices=ACTIVE_CHOICES, verbose_name='Опубликовано')
    views_count = models.IntegerField(default=0, verbose_name='просмотров')

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='Владелец', **NULLABLE)
    is_active = models.BooleanField(default=True, choices=ACTIVE_CHOICES, verbose_name='Активна')

    def __str__(self):
        return f'{self.title}, {self.slug}'

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Пост'

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.models import Post


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ('title', 'description', 'image', 'is_published')
    success_url = reverse_lazy('blog:blog')
    extra_context = {
        'title': 'Создать блог'
    }

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ('title', 'description', 'image', 'is_published')
    extra_context = {
        'title': 'Изменить блог'
    }

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if not self.request.user.is_superuser:
            if self.object.owner != self.request.user or self.request.user.filter(groups__name='manager').exists():
                raise Http404
        return self.object

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:view', args=[self.object.pk])


class BlogListView(ListView):
    model = Post
    extra_context = {
        'title': 'Блог'
    }

    def get_queryset(self):
        user = self.request.user

        if user.is_authenticated:  # для зарегистрированных пользователей
            if user.is_staff or user.is_superuser:  # для работников и суперпользователя
                queryset = super().get_queryset().order_by('pk')

            else:  # для остальных пользователей
                # Получаем queryset, результат фильтрации по условию owner=user
                queryset_1 = super().get_queryset().filter(owner=user).order_by('pk')
                # Получаем queryset, результат фильтрации по условию is_published=True
                queryset_2 = super().get_queryset().filter(is_published=True, is_active=True).order_by('pk')
                # Объединяем два queryset с использованием метода union()
                queryset = queryset_2.union(queryset_1)
                # queryset = super().get_queryset().filter(owner=user).order_by('pk')

        else:  # для незарегистрированных пользователей
            queryset = super().get_queryset().filter(
                is_published=True).order_by('-pk')
        return queryset


class BlogDetailView(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.get_object()
        post.views_count += 1
        post.save()
        context['title'] = post.title
        return context


class BlogDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:blog')
    extra_context = {
        'title': 'Удалить блог'
    }

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if not self.request.user.is_superuser:
            if self.object.owner != self.request.user or self.request.user.filter(groups__name='manager').exists():
                raise Http404
        return self.object

blog/templates/blog/post_confirm_delete.html
{% extends 'users/base.html' %}

{% block content %}
{% load my_tags %}

<div class="text-center container">
    <div class="col-12">
        <div class="row">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        <p>Хотите удалить блог?: "{{ object.name }}"</p>
                        {% csrf_token %}
                        <button type="submit" class="btn btn-lg btn-block btn-outline-danger">Удалить</button>
                        <a type="button" href="{% url 'blog:blog'%}" class="btn btn-lg btn-block btn-outline-success">Возврат</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'users/base.html' %}

{% block content %}
{% load my_tags %}

<div class="container">
    <div class="col-12">
        <div class="card h-100">
            <img src="{% my_media_tag object.image %}" class="card-img-top mb-3" alt="...">
            <div class="card-body">
                <h5 class="card-title mb-3">{{ object.title|title }}</h5>
                <h6 class="card-subtitle mb-3 text-body-secondary">{{ object.slug }}</h6>
                <p class="card-text">{{ object.description }}</p>
                <p class="card-text">Автор: {{ object.owner }}</p>
                <a href="{% url 'blog:blog' %}" type="button" class="btn btn-sm btn-outline-success mb-3">
                    Возврат к блогам</a>
            </div>
            <div class="card-footer">
                <small class="text-body-secondary ms-5">Создан {{ object.created_at }}</small>
                <small class="text-body-secondary ms-5">Количество просмотров {{ object.views_count }}</small>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/post_form.html
{% extends 'users/base.html' %}
{% block content %}
{% load my_tags %}

<div class="text-center container">
    <div class="col-12">
        <div class="row">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-lg btn-block btn-outline-success">
                            {% if object %}
                            Изменить
                            {% else %}
                            Отправить
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/post_list.html
{% extends 'users/base.html' %}
{% load my_tags %}
{% block content %}

{% if request.user.is_authenticated %}
{% if not user|has_group:"manager" %}
<div class="text-center container">
    <a class="btn btn-outline-success" href="{% url 'blog:create' %}" type="button">Создать блог</a>
</div>
{% endif %}
{% endif %}

<div class="container mt-5">
<div class="row row-cols-1 row-cols-md-3 g-4">
    {% for object in post_list %}
    <div class="col">
        <div class="card h-100">
            <img src="{% my_media_tag object.image %}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">{{ object.title|title }}</h5>
                <p class="card-text">{{ object.description|truncatechars:100 }}</p>
                <p class="card-text">Автор: {{ object.owner }}</p>
            </div>
            <div class="card-footer">
                <a href="{% url 'blog:view' object.pk %}" type="button"
                   class="btn btn-sm btn-outline-success">Просмотр</a>
                {% if request.user.is_authenticated %}
                {% if not user|has_group:"manager" %}
                {% if user == object.owner or request.user.is_staff %}
                <a href="{% url 'blog:edit' object.pk %}" type="button"
                   class="btn btn-sm btn-outline-secondary">Редактировать</a>
                <a href="{% url 'blog:delete' object.pk %}" type="button"
                   class="btn btn-sm btn-outline-danger">Удалить</a>
                {% endif %}
                {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>
</div>

{% endblock %}