blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', cache_page(60)(BlogListView.as_view()), name='blog'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
]

clients/urls.py
from django.urls import path
from clients.apps import ClientsConfig
from clients.views import ClientListView, ClientCreateView, ClientUpdateView, \
    ClientDetailView, ClientDeleteView

app_name = ClientsConfig.name

urlpatterns = [
    path('', ClientListView.as_view(), name='list'),
    path('create/', ClientCreateView.as_view(), name='create'),
    path('view/<int:pk>/', ClientDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', ClientUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', ClientDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('users.urls', namespace='users')),
                  path('client/', include('clients.urls', namespace='clients')),
                  path('distribution/', include('distribution.urls', namespace='distribution')),
                  path('blog', include('blog.urls', namespace='blog')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

distribution/urls.py
from django.urls import path
from distribution.apps import DistributionConfig
from distribution.views import MessageListView, MessageCreateView, MessageUpdateView, MessageDetailView, \
    MessageDeleteView, MailingSettingsListView, MailingSettingsDetailView, \
    MailingSettingsDeleteView, LogListView, LogDetailView, LogDeleteView, MailingSettingsCreateView, \
    MailingSettingsUpdateView, toggle_active

app_name = DistributionConfig.name

urlpatterns = [
    path('messages/', MessageListView.as_view(), name='message_list'),
    path('message_create/', MessageCreateView.as_view(), name='message_create'),
    path('message_edit/<int:pk>/', MessageUpdateView.as_view(), name='message_edit'),
    path('message/<int:pk>/', MessageDetailView.as_view(), name='message_view'),
    path('message_delete/<int:pk>/', MessageDeleteView.as_view(), name='message_delete'),

    path('list/', MailingSettingsListView.as_view(), name='list'),
    path('toggle-active/<int:pk>/', toggle_active, name='toggle_active'),
    path('view/<int:pk>/', MailingSettingsDetailView.as_view(), name='view'),
    path('create/', MailingSettingsCreateView.as_view(), name='create'),
    path('edit/<int:pk>/', MailingSettingsUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', MailingSettingsDeleteView.as_view(), name='delete'),

    path('logs', LogListView.as_view(), name='log_list'),
    path('log/<int:pk>/', LogDetailView.as_view(), name='log_detail'),
    path('log_delete/<int:pk>/', LogDeleteView.as_view(), name='log_delete'),
]

users/urls.py
from django.urls import path

from django.contrib.auth.views import LoginView, LogoutView

from users.apps import UsersConfig
from users.views import MainPage, RegisterView, UserUpdateView, generate_new_password, UserConfirmEmailView, \
    UserConfirmationSentView, UserConfirmedView, UserConfirmationFailView, regenerate_password, UserListView, \
    toggle_active

app_name = UsersConfig.name

urlpatterns = [
    path('', MainPage.as_view(), name='main'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('users/', UserListView.as_view(), name='user_list'),
    path('toggle-active/<int:pk>/', toggle_active, name='toggle_active'),

    path('profile/genpassword/', generate_new_password, name='generate_new_password'),
    path('regenerations/', regenerate_password, name='regenerate_password'),
    path('email_confirmation_sent/', UserConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('confirm_email/<str:uidb64>/<str:token>/', UserConfirmEmailView.as_view(), name='confirm_email'),
    path('email_confirmed/', UserConfirmedView.as_view(), name='email_confirmed'),
    path('email_confirmation_failed/', UserConfirmationFailView.as_view(), name='email_confirmation_failed'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    DoesNotExist = None
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')

    phone = models.CharField(max_length=35, verbose_name='телефон', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    country = models.CharField(max_length=50, verbose_name='страна', **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from users.models import User
from django import forms


class UserRegisterForm(UserCreationForm):
    """
    Форма регистрации пользователя
    """

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class UserProfileForm(UserChangeForm):
    """
    Форма профиля пользователя
    """

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'avatar', 'country')

    def __init__(self, *args, **kwargs):
        """
        Дополнительные настройки
        """
        super().__init__(*args, **kwargs)

        # Позволяет не выводить в профиле поле пароля
        self.fields['password'].widget = forms.HiddenInput()

        # передаем в шаблон контроль формы
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

users/views.py
import random

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import PasswordResetDoneView
from django.core.cache import cache

from django.core.mail import send_mail
from django.http import Http404
from django.utils.crypto import get_random_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import View
from django.views.generic import CreateView, UpdateView, TemplateView, ListView
from django.urls import reverse_lazy, reverse
from django.core.cache import cache
from blog.models import Post
from clients.models import Client
from config import settings
from distribution.models import MailingSettings
from users.forms import UserRegisterForm, UserProfileForm
from users.models import User
from django.shortcuts import redirect, render
from django.contrib.auth import login


class MainPage(LoginRequiredMixin, TemplateView):
    login_url = 'users:login'
    template_name = 'users/main.html'
    extra_context = {
        'title': 'Сайт отправки рассылок'
    }

    def get_context_data(self, *args, **kwargs):
        user = self.request.user
        if self.request.method == 'GET':
            if settings.CACHE_ENABLED:
                key = f'cached_statistics'
                cached_context = cache.get(key)
                if cached_context is None:
                    context = super().get_context_data(*args, **kwargs)
                    if not user.is_staff:
                        context['mailing_count'] = MailingSettings.objects.filter(owner=user).count()
                        context['enabled_mailing'] = MailingSettings.objects.filter(owner=user).filter(
                            status='Запущена').count()
                        unic_client = []
                        for client in Client.objects.filter(owner=user):
                              unic_client.append(client.email)
                        context['unique_clients'] = len(set(unic_client))
                        all_blog_posts = Post.objects.all()
                        random.shuffle(list(all_blog_posts))
                        context['three_random_posts'] = all_blog_posts[:3]
                    else:
                        context['mailing_count'] = MailingSettings.objects.all().count()
                        context['enabled_mailing'] = MailingSettings.objects.all().filter(status='Запущена').count()
                        unic_client = []
                        for client in Client.objects.all():
                            unic_client.append(client.email)
                        context['unique_clients'] = len(set(unic_client))
                        main_page_context = {
                            'mailing_count': context['mailing_count'],
                            'enabled_mailing': context['enabled_mailing'],
                            'unique_clients': context['unique_clients']
                        }
                        cache.set(key, main_page_context)
                        all_blog_posts = Post.objects.all()
                        random.shuffle(list(all_blog_posts))
                        context['three_random_posts'] = all_blog_posts[:3]
                    return context
                else:
                    context = super().get_context_data(*args, **kwargs)
                    context['mailing_count'] = cached_context['mailing_count']
                    context['enabled_mailing'] = cached_context['enabled_mailing']
                    context['unique_clients'] = cached_context['unique_clients']
                    all_blog_posts = Post.objects.all()
                    random.shuffle(list(all_blog_posts))
                    context['three_random_posts'] = all_blog_posts[:3]
                return context


class RegisterView(CreateView):
    """ Регистрация нового пользователя и его валидация через письмо на email пользователя """
    form_class = UserRegisterForm
    template_name = "users/register.html"
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        user.save()

        # формируем токен и ссылку для подтверждения регистрации
        token = default_token_generator.make_token(user)
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        activation_url = reverse_lazy('users:confirm_email', kwargs={'uidb64': uid, 'token': token})

        current_site = '127.0.0.1:8000'

        send_mail(
            subject='Регистрация на платформе',
            message=f"Завершите регистрацию, перейдя по ссылке: http://{current_site}{activation_url}",
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[user.email]
        )
        return redirect('users:email_confirmation_sent')


class UserConfirmationSentView(PasswordResetDoneView):
    """ Выводит информацию об отправке на почту подтверждения регистрации """
    template_name = "users/registration_sent_done.html"
    extra_context = {
        'title': 'На почту отправлена ссылка подтверждения регистрации'
    }


class UserConfirmEmailView(View):
    """ Подтверждение пользователем регистрации """

    def get(self, request, uidb64, token):
        try:
            uid = urlsafe_base64_decode(uidb64)
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            login(request, user)
            return redirect('users:email_confirmed')
        else:
            return redirect('users:email_confirmation_failed')


class UserConfirmedView(TemplateView):
    """ Выводит информацию об успешной регистрации пользователя """
    template_name = 'users/registration_confirmed.html'


class UserConfirmationFailView(View):
    """ Выводит информацию о невозможности зарегистрировать пользователя """
    template_name = 'users/email_confirmation_failed.html'


class UserUpdateView(UpdateView, LoginRequiredMixin):
    """ Контроллер профиля пользователя """
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        #""" Позволяет делать необязательным передачу pk объекта но пользователи не могут завести свой профиль """
        #if not self.request.user.is_superuser:
        #    if self.object.owner != self.request.user or self.request.user.filter(groups__name='manager').exists():
        #        raise Http404
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Редактирование профиля'
        return context


class UserListView(PermissionRequiredMixin, LoginRequiredMixin, ListView):
    model = User
    permission_required = 'users.view_user'  # Указание правила доступа к контроллеру
    extra_context = {
        'title': 'Список пользователей'
    }

    def get_queryset(self):
        user = self.request.user
        if user.is_superuser:  # для суперпользователя
            queryset = super().get_queryset()
        elif user.is_staff:
            queryset = super().get_queryset().filter(is_staff=False)
        else:  # для остальных пользователей
            queryset = None
        return queryset


def toggle_active(request, pk):
    if request.user.is_staff:
        user = User.objects.get(pk=pk)
        user.is_active = not user.is_active
        user.save()
        return redirect('users:user_list')


@login_required
def generate_new_password(request):
    """ Генерирует новый пароль пользователя """
    new_password = get_random_string(length=9)

    send_mail(
        subject='Новый пароль',
        message=f'Ваш новый пароль: {new_password}',
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[request.user.email]
    )

    request.user.set_password(new_password)
    request.user.save()

    return redirect(reverse('users:main'))


def regenerate_password(request):
    """ Генерирует новый пароль пользователя """
    if request.method == 'POST':
        email = request.POST.get('email')
        # Получаем пользователя по email
        user = User.objects.get(email=email)

        # Генерируем новый пароль
        new_password = get_random_string(length=9)

        # Изменяем пароль пользователя
        user.set_password(new_password)
        user.save()

        # Отправляем письмо с новым паролем
        send_mail(
            subject='Восстановление пароля',
            message=f'Ваш новый пароль: {new_password}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[email],
        )

        return redirect(reverse('users:main'))
    return render(request, 'users/regenerate_password.html')

users/templates/users/base.html
{% load static %}

<!doctype html>
<html lang="ru">
<head>
    <script src="{% static 'js/color-modes.js'%}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.115.4">

    <title>Сайт рассылок</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/album/">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Сайт отправки рассылок</h5>
    <nav class="ms-5">

        {% if user.is_authenticated %}
        <a class="p-2 btn btn-outline-warning" href="{% url 'users:main' %}">Главная</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'blog:blog' %}">Блог</a>
        <a class="p-2 btn btn-outline-danger" href="{% url 'users:logout' %}">Выйти</a>
        <a class="p-2 btn btn-outline-info" href="{% url 'users:profile' %}">Профиль</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'clients:list' %}">Клиенты</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'distribution:list' %}">Рассылки</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'distribution:message_list' %}">Сообщения</a>
        <a class="p-2 btn btn-outline-danger" href="{% url 'distribution:log_list' %}">Логи</a>
        {% else %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:main' %}">Главная</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'blog:blog' %}">Блог</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Войти</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
        {% if user.is_staff %}
        <a class="p-2 btn btn-outline-info" href="{% url 'users:user_list' %}">Пользователи</a>
        {% endif %}

    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title|title }}</h1>
</div>


<div>
    <!--Блок кода страницы-->
    {% block content %}
    {% endblock %}
</div>


<div>
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                Сайт отправки рассылок
                <small class="d-block mb-3 text-muted">Aleks-1966 - {% now 'Y' %}</small>
            </div>
        </div>
    </footer>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>
</body>
</html>

users/templates/users/email_confirmation_failed.html
{% extends 'users/base.html' %}

{% block content %}

<div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">Ошибка</h4>
    <p>Не удалось подтвердить вашу электронную почту. Попробуйте еще раз</p>
</div>

{% endblock %}

users/templates/users/login.html
{% extends 'users/base.html' %}

{% block content %}

<div class="text-center container">
    <div class="card col-8">
        <form method="post" enctype="multipart/form-data">

            <div class="card-header">
                <h4 class="card-title">Вход</h4>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Войти</button>
            </div>
            <div class="card-footer">

                <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>

                <h5>Сгенирировать пароль на почту если забыли пароль</h5>
                <a href="{% url 'users:regenerate_password' %}" type="button" class="btn btn-sm btn-outline-secondary">Сгенирировать
                    пароль</a>
            </div>
        </form>
    </div>
</div>

{% endblock %}

users/templates/users/main.html
{% extends 'users/base.html' %}
{% load my_tags %}

{% block content %}

<div class="container col-8 mt-2 mb-5">
    <div class="card">
        <div class="card-header text-center">
            <h1>Статистика</h1>
        </div>
        <div class="card-body">
            <div class="row text-center ">
                <div class="col-12">
                    <table class="table">
                        <thead>
                        <tr>
                            <th><h4>Всего рассылок</h4></th>
                            <th><h4>Активных рассылок</h4></th>
                            <th><h4>Уникальных клиентов</h4></th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td><h4>{{ mailing_count }}</h4></td>
                            <td><h4>{{ enabled_mailing }}</h4></td>
                            <td><h4>{{ unique_clients }}</h4></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for post in three_random_posts %}

        <div class="col">
            <div class="card h-100">
                <img src="{% my_media_tag post.image %}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{ post.title|title }}</h5>
                    <p class="card-text">{{ post.description|truncatechars:64 }}</p>
                </div>
                <div class="card-footer">
                    <a href="{% url 'blog:view' post.pk %}" class="btn btn-primary">Подробнее</a>
                </div>
            </div>
        </div>

        {% endfor %}
    </div>
</div>
{% endblock %}

users/templates/users/regenerate_password.html
{% extends 'users/base.html' %}

{% block content %}

<div class="container">
    <div class="row text-start">
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Сгенирировать пароль</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="exampleFormControlInput1" class="form-label">Email address</label>
                            <input type="email" name="email" class="form-control" id="exampleFormControlInput1"
                                   placeholder="name@example.com">
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Сгенирировать пароль
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/register.html
{% extends 'users/base.html' %}

{% block content %}

<div class="text-center container">
    <div class="card col-8">
        <form method="post" enctype="multipart/form-data">
            <div class="card-header">
                <h4 class="card-title">Регистрация</h4>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
                <a class="p-2 btn btn-outline-primary" href="{% url 'users:main' %}">Главная</a>
            </div>
        </form>
    </div>
</div>

{% endblock %}

users/templates/users/registration_confirmed.html
{% extends 'users/base.html' %}

{% block content %}

<div class="alert alert-success" role="alert">
    <h4 class="alert-heading">Успешно</h4>
    <p>Ваша электронная почта подтверждена</p>
</div>
<a class="p-2 btn btn-outline-primary" href="{% url 'users:main' %}">Главная</a>

{% endblock %}

users/templates/users/registration_sent_done.html
{% extends 'users/base.html' %}

{% block content %}

<div class="alert alert-warning" role="alert">
    <h4 class="alert-heading">Вам на указанную почту при регистрации, отправлено письмо</h4>
    <br>
    <p>Для успешной регистрации перейдите по ссылке, указанной в письме</p>
</div>

{% endblock %}

users/templates/users/user_form.html
{% extends 'users/base.html' %}

{% block content %}

<div class="text-center container">
    <div class="card col-8">
        <div class="card-header">
            <h4 class="card-title">Профиль</h4>
        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Сохранить</button>
            </form>
        </div>
        <div class="card-footer">
            <a class="btn btn-danger" href="{% url 'users:generate_new_password' %}">Сгенирировать пароль</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:main' %}">Главная</a>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/user_list.html
{% extends 'users/base.html' %}

{% block content %}

<div class="container text-center">
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">id Пользователя</th>
            <th scope="col">Почта</th>
            <th scope="col">страна</th>
            <th scope="col">телефон</th>
            <th scope="col">Статус</th>
        </tr>
        </thead>
        <tbody>

        {% for user in object_list %}
        {% if not user.is_superuser %}

        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ user.pk }}</td>
            <td>{{ user.email }}</td>
            <td>{{ user.country }}</td>
            <td>{{ user.phone }}</td>
            {% if user.is_active %}
            <td>
                <a href="{% url 'users:toggle_active' user.pk %}" type="button"
                   class="btn btn-success">True</a>
            </td>
            {% else %}
            <td>
                <a href="{% url 'users:toggle_active' user.pk %}" type="button"
                   class="btn btn-danger">False</a>
            </td>
        </tr>
        {% endif %}
        {% endif %}
        {% endfor %}

        </tbody>
    </table>
</div>

{% endblock %}