blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', cache_page(60)(BlogListView.as_view()), name='blog'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
]

clients/urls.py
from django.urls import path
from clients.apps import ClientsConfig
from clients.views import ClientListView, ClientCreateView, ClientUpdateView, \
    ClientDetailView, ClientDeleteView

app_name = ClientsConfig.name

urlpatterns = [
    path('', ClientListView.as_view(), name='list'),
    path('create/', ClientCreateView.as_view(), name='create'),
    path('view/<int:pk>/', ClientDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', ClientUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', ClientDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('users.urls', namespace='users')),
                  path('client/', include('clients.urls', namespace='clients')),
                  path('distribution/', include('distribution.urls', namespace='distribution')),
                  path('blog', include('blog.urls', namespace='blog')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clients/models.py
from django.db import models

from config import settings

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    """
    Модель клиента содержащая email и инфу клиента
    """
    email = models.EmailField(verbose_name='Email')
    name = models.CharField(max_length=64, verbose_name='Имя')
    surname = models.CharField(max_length=64, verbose_name='Фамилия')
    patronymic = models.CharField(max_length=64, **NULLABLE, verbose_name='Отчество')
    comment = models.TextField(**NULLABLE, default=None, verbose_name='Комментарий')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='Владелец', **NULLABLE)

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'
        ordering = ('surname', 'name',)

clients/forms.py
from django import forms
from .models import Client


class StyleFormMixin:
    """
    Миксин форма со стилем форм
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ClientForm(StyleFormMixin, forms.ModelForm):
    """
    Форма для модели клиента
    """

    class Meta:
        model = Client
        exclude = ('owner',)  # Использование всех полей, кроме перечисленных

clients/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from .models import Client
from .forms import ClientForm


class ClientListView(LoginRequiredMixin, ListView):
    model = Client
    extra_context = {
        'title': 'Список клиентов'
    }

    def get_queryset(self):
        user = self.request.user
        if user.is_staff or user.is_superuser:  # для работников и суперпользователя
            queryset = super().get_queryset()
        else:  # для остальных пользователей
            queryset = super().get_queryset().filter(owner=user)
        return queryset


class ClientDetailView(LoginRequiredMixin, DetailView):
    model = Client

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        client = self.get_object()
        context['title'] = client.email
        return context


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    extra_context = {
        'title': 'Добавить клиента'
    }

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('clients:view', args=[self.object.pk])


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    form_class = ClientForm
    extra_context = {
        'title': 'Изменить клиента'
    }

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if not self.request.user.is_superuser:
            if self.object.owner != self.request.user or self.request.user.filter(groups__name='manager').exists():
                raise Http404
        return self.object

    def get_success_url(self):
        return reverse('clients:view', args=[self.object.pk])


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('clients:list')
    extra_context = {
        'title': 'Удалить клиента'
    }

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if not self.request.user.is_superuser:
            if self.object.owner != self.request.user or self.request.user.filter(groups__name='manager').exists():
                raise Http404
        return self.object

clients/templates/clients/client_confirm_delete.html
{% extends 'users/base.html' %}

{% block content %}

<div class="text-center container">
    <div class="col-12">
        <div class="row">
            <div class="card col-8">
                <div class="card-body">
                    <h5 class="card-title">Хотите удалить клиента: {{ client.email }}</h5>
                    <p class="card-text mb-3">Имя: {{ client.name|title }}</p>
                    <p class="card-text mb-3">Фамилия: {{ client.surname|title }}</p>
                    <p class="card-text mb-3">Отчество: {{ client.patronymic|title }}</p>
                    <p class="card-text mb-3">Комментарий: {% if client.comment %}
                        {{ client.comment }}
                        {% else %}
                        None
                        {% endif %}</p>
                </div>
                <div class="card-footer">

                    {% if request.user.is_staff %}
                    <p class="card-text mb-3">Владелец: {{ client.owner }}</p>
                    {% endif %}
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Delete</button>
                        <a type="button" href="{% url 'clients:list'%}"
                           class="btn btn-lg btn-block btn-outline-primary">return</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

clients/templates/clients/client_detail.html
{% extends 'users/base.html' %}

{% block content %}

<div class="container">
    <div class="card col-8">
        <div class="card-body">

            <h5 class="card-title">email: {{ client.email }}</h5>
            <p class="card-text mb-3">Имя: {{ client.name|title }}</p>
            <p class="card-text mb-3">Фамилия: {{ client.surname|title }}</p>
            <p class="card-text mb-3">Отчество: {{ client.patronymic|title }}</p>
            <p class="card-text mb-3">Комментарий:
                {% if client.comment %}
                {{ client.comment }}
                {% else %}
                None
                {% endif %}</p>

        </div>
        <div class="card-footer">

            {% if request.user.is_staff %}
            <p class="card-text mb-3">Владелец: {{ client.owner }}</p>
            {% endif %}
            <a type="button" href="{% url 'clients:list'%}"
               class="btn btn-lg btn-block btn-outline-primary">return</a>

        </div>
    </div>
</div>

{% endblock %}

clients/templates/clients/client_form.html
{% extends 'users/base.html' %}

{% block content %}

<div class="text-center container">
    <form method="post" enctype="multipart/form-data">
        <div class="card col-8">
            <div class="card-body">

                {% csrf_token %}
                {{ form.as_p }}

                <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                    {% if object %}
                    Изменить
                    {% else %}
                    Создать
                    {% endif %}
                </button>
                <a type="button" href="{% url 'clients:list'%}"
                           class="btn btn-lg btn-block btn-outline-primary">return</a>

            </div>
        </div>
    </form>
</div>

{% endblock %}

clients/templates/clients/client_list.html
{% extends 'users/base.html' %}
{% load my_tags %}
{% block content %}

{% if not user|has_group:"manager" %}
<div class="text-center container">
    <a class="btn btn-primary" href="{% url 'clients:create' %}" type="button">Добавить клиента</a>
</div>
{% endif %}

<div class="container text-center">
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Email</th>
            <th scope="col">Имя</th>
            <th scope="col">Фамилия</th>
            <th scope="col">Отчество</th>
            {% if request.user.is_staff %}
            <th scope="col">Владелец</th>
            {% endif %}
            <th scope="col">Действия</th>
        </tr>
        </thead>
        <tbody>

        {% for client in object_list %}

        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ client.email }}</td>
            <td>{{ client.name|title }}</td>
            <td>{{ client.surname|title }}</td>
            <td>{{ client.patronymic|title }}</td>
            {% if request.user.is_staff %}
            <th>{{ client.owner }}</th>
            {% endif %}
            <td>
                <div class="btn-group" role="group" aria-label="Basic outlined example">
                    <a href="{% url 'clients:view' client.pk %}" type="button"
                       class="btn btn-sm btn-outline-secondary">View</a>
                    {% if not user|has_group:"manager" %}
                    <a href="{% url 'clients:edit' client.pk %}" type="button"
                       class="btn btn-sm btn-outline-secondary">Edit</a>
                    <a href="{% url 'clients:delete' client.pk %}" type="button"
                       class="btn btn-sm btn-outline-secondary">Delete</a>
                    {% endif %}
                </div>
            </td>
        </tr>

        {% endfor %}

        </tbody>
    </table>
</div>

{% endblock %}