blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', cache_page(60)(BlogListView.as_view()), name='blog'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('users.urls', namespace='users')),
                  path('client/', include('clients.urls', namespace='clients')),
                  path('distribution/', include('distribution.urls', namespace='distribution')),
                  path('blog', include('blog.urls', namespace='blog')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

distribution/urls.py
from django.urls import path
from distribution.apps import DistributionConfig
from distribution.views import MessageListView, MessageCreateView, MessageUpdateView, MessageDetailView, \
    MessageDeleteView, MailingSettingsListView, MailingSettingsDetailView, \
    MailingSettingsDeleteView, LogListView, LogDetailView, LogDeleteView, MailingSettingsCreateView, \
    MailingSettingsUpdateView, toggle_active

app_name = DistributionConfig.name

urlpatterns = [
    path('messages/', MessageListView.as_view(), name='message_list'),
    path('message_create/', MessageCreateView.as_view(), name='message_create'),
    path('message_edit/<int:pk>/', MessageUpdateView.as_view(), name='message_edit'),
    path('message/<int:pk>/', MessageDetailView.as_view(), name='message_view'),
    path('message_delete/<int:pk>/', MessageDeleteView.as_view(), name='message_delete'),

    path('list/', MailingSettingsListView.as_view(), name='list'),
    path('toggle-active/<int:pk>/', toggle_active, name='toggle_active'),
    path('view/<int:pk>/', MailingSettingsDetailView.as_view(), name='view'),
    path('create/', MailingSettingsCreateView.as_view(), name='create'),
    path('edit/<int:pk>/', MailingSettingsUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', MailingSettingsDeleteView.as_view(), name='delete'),

    path('logs', LogListView.as_view(), name='log_list'),
    path('log/<int:pk>/', LogDetailView.as_view(), name='log_detail'),
    path('log_delete/<int:pk>/', LogDeleteView.as_view(), name='log_delete'),
]

distribution/models.py
from django.db import models

from clients.models import Client
from config import settings

NULLABLE = {'blank': True, 'null': True}


class Message(models.Model):
    title = models.CharField(max_length=100, verbose_name='Тема письма')
    text = models.TextField(verbose_name='Письмо')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='Владелец', **NULLABLE)

    def __str__(self):
        return f'message title:{self.title}'

    class Meta:
        verbose_name = 'сообщение'
        verbose_name_plural = 'сообщения'
        ordering = ('title',)


class MailingSettings(models.Model):
    DAILY = "Раз в день"
    WEEKLY = "Раз в неделю"
    MONTHLY = "Раз в месяц"

    PERIODICITY_CHOICES = [
        (DAILY, "Раз в день"),
        (WEEKLY, "Раз в неделю"),
        (MONTHLY, "Раз в месяц"),
    ]

    CREATED = 'Создана'
    STARTED = 'Запущена'
    COMPLETED = 'Завершена'

    STATUS_CHOICES = [
        (COMPLETED, "Завершена"),
        (CREATED, "Создана"),
        (STARTED, "Запущена"),
    ]

    ACTIVE_CHOICES = ((True, 'Активна'), (False, 'На модерации'))

    start_time = models.DateTimeField(verbose_name='Дата начала рассылки')
    end_time = models.DateTimeField(verbose_name='Дата окончания рассылки')
    next_send = models.DateTimeField(**NULLABLE, verbose_name='Дата следующей рассылки')
    periodicity = models.CharField(choices=PERIODICITY_CHOICES, max_length=50, verbose_name='Периодичность')
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default=CREATED, verbose_name='Статус рассылки')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    message = models.ForeignKey(Message, on_delete=models.CASCADE, default=None, verbose_name='Сообщение')
    clients = models.ManyToManyField(Client, verbose_name='Клиенты рассылки')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='Владелец', **NULLABLE)
    is_active = models.BooleanField(default=True, choices=ACTIVE_CHOICES, verbose_name='Активна')

    def __str__(self):
        return f'time: {self.start_time} - {self.end_time}, periodicity: {self.periodicity}, status: {self.status}'

    class Meta:
        verbose_name = 'настройки рассылки'
        verbose_name_plural = 'настройки рассылки'
        ordering = ('created_at',)


class MailingLog(models.Model):
    time = models.DateTimeField(verbose_name='Дата и время создания лога', auto_now_add=True)
    status = models.BooleanField(verbose_name='Статус попытки')
    server_response = models.CharField(max_length=1000, verbose_name='Ответ почтового сервера', **NULLABLE)
    mailing = models.ForeignKey(MailingSettings, on_delete=models.CASCADE, verbose_name='Рассылка')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, **NULLABLE, on_delete=models.SET_NULL, verbose_name='Владелец')

    def __str__(self):
        return f'{self.time} {self.status}'

    class Meta:
        verbose_name = 'лог'
        verbose_name_plural = 'логи'
        ordering = ('time',)

distribution/forms.py
from django.forms import ModelForm

from clients.models import Client
from distribution.models import Message, MailingSettings


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class MailingSettingsForm(StyleFormMixin, ModelForm):
    class Meta:
        model = MailingSettings
        fields = ('start_time', 'end_time', 'periodicity', 'clients', 'message',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        owner = kwargs.pop('initial').get('owner')
        if not owner.is_superuser:
            self.fields['clients'].queryset = Client.objects.all().filter(owner=owner)
            self.fields['message'].queryset = Message.objects.all().filter(owner=owner)


class MessageForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Message
        fields = ('title', 'text',)

distribution/views.py
import calendar
from datetime import timedelta, datetime

from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import inlineformset_factory
from django.http import Http404
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.utils import timezone
from django.views import View
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from .forms import MailingSettingsForm, MessageForm
from .models import MailingSettings, MailingLog, Message


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    extra_context = {
        'title': 'Создать сообщение'
    }

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('distribution:message_list')


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm
    extra_context = {
        'title': 'Редактировать сообщение'
    }

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if not self.request.user.is_superuser:
            if self.object.owner != self.request.user or self.request.user.filter(groups__name='manager').exists():
                raise Http404
        return self.object

    def form_valid(self, form):
        self.object = form.save()
        self.object.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('distribution:message_view', args=[self.object.pk])


class MessageListView(LoginRequiredMixin, ListView):
    model = Message

    def get_queryset(self):
        user = self.request.user
        if user.is_staff or user.is_superuser:  # для работников и суперпользователя
            queryset = super().get_queryset()
        else:  # для остальных пользователей
            queryset = super().get_queryset().filter(owner=user)
        return queryset

    def get_context_data(self, *args, **kwargs):
        user = self.request.user
        context_data = super().get_context_data(*args, **kwargs)
        context_data['title'] = 'Список Сообщений'
        return context_data


class MessageDetailView(LoginRequiredMixin, DetailView):
    model = Message

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        message = self.get_object()
        context_data['title'] = message.title[:20]
        return context_data


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('distribution:message_list')
    extra_context = {
        'title': 'Удалить сообщение'
    }

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if not self.request.user.is_superuser:
            if self.object.owner != self.request.user or self.request.user.filter(groups__name='manager').exists():
                raise Http404
        return self.object


class MailingSettingsCreateView(LoginRequiredMixin, CreateView):
    model = MailingSettings
    form_class = MailingSettingsForm
    extra_context = {
        'title': 'Создать рассылку'
    }

    def get_initial(self):
        initial = super().get_initial()
        initial['owner'] = self.request.user
        return initial

    def form_valid(self, form):
        current_time = timezone.localtime(timezone.now())
        new_mailing = form.save()
        new_mailing.save()
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        if form.is_valid():
            clients = form.cleaned_data['clients']
            new_mailing = form.save()
            if new_mailing.start_time > current_time:
                new_mailing.next_send = new_mailing.start_time
            else:
                if new_mailing.periodicity == "Раз в день":
                    new_mailing.next_send = new_mailing.start_time + timedelta(days=1)

                if new_mailing.periodicity == "Раз в неделю":
                    new_mailing.next_send = new_mailing.start_time + timedelta(days=7)

                if new_mailing.periodicity == "Раз в месяц":
                    today = datetime.today()
                    days = calendar.monthrange(today.year, today.month)[1]
                    new_mailing.next_send = current_time + timedelta(days=days)

                for client in clients:
                    new_mailing.clients.add(client.pk)
                new_mailing.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('distribution:list')


class MailingSettingsUpdateView(LoginRequiredMixin, UpdateView):
    model = MailingSettings
    form_class = MailingSettingsForm
    extra_context = {
        'title': 'Редактировать рассылку'
    }

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if not self.request.user.is_superuser:
            if self.object.owner != self.request.user or self.request.user.filter(groups__name='manager').exists():
                raise Http404
        return self.object

    def get_initial(self):
        initial = super().get_initial()
        initial['owner'] = self.request.user
        return initial

    def form_valid(self, form):
        current_time = timezone.localtime(timezone.now())
        new_mailing = form.save()
        new_mailing.save()
        self.object = form.save()
        self.object.save()
        if form.is_valid():
            clients = form.cleaned_data['clients']
            new_mailing = form.save()
            if new_mailing.start_time > current_time:
                new_mailing.next_send = new_mailing.start_time
            else:
                if new_mailing.periodicity == "Раз в день":
                    new_mailing.next_send = new_mailing.start_time + timedelta(days=1)

                if new_mailing.periodicity == "Раз в неделю":
                    new_mailing.next_send = new_mailing.start_time + timedelta(days=7)

                if new_mailing.periodicity == "Раз в месяц":
                    today = datetime.today()
                    days = calendar.monthrange(today.year, today.month)[1]
                    new_mailing.next_send = new_mailing.start_time + timedelta(days=days)

                for client in clients:
                    new_mailing.clients.add(client.pk)
                new_mailing.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('distribution:view', args=[self.object.pk])


class MailingSettingsListView(LoginRequiredMixin, ListView):
    model = MailingSettings

    def get_queryset(self):
        user = self.request.user
        if user.is_staff or user.is_superuser:  # для работников и суперпользователя
            queryset = super().get_queryset()
        else:  # для остальных пользователей
            queryset = super().get_queryset().filter(owner=user)
        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['title'] = 'Список рассылок'

        context_data['all'] = context_data['object_list'].count()
        context_data['active'] = context_data['object_list'].filter(status=MailingSettings.STARTED).count()
        context_data['completed'] = context_data['object_list'].filter(status=MailingSettings.COMPLETED).count()

        return context_data


def toggle_active(request, pk):
    if request.user.is_staff:
        distribution = MailingSettings.objects.get(pk=pk)
        distribution.is_active = not distribution.is_active
        distribution.save()
        return redirect('distribution:list')


class MailingSettingsDetailView(LoginRequiredMixin, DetailView):
    model = MailingSettings

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['title'] = f'Детали рассылки:'
        return context_data


class MailingSettingsDeleteView(LoginRequiredMixin, DeleteView):
    model = MailingSettings

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if not self.request.user.is_superuser:
            if self.object.owner != self.request.user or self.request.user.filter(groups__name='manager').exists():
                raise Http404
        return self.object

    def get_success_url(self):
        return reverse('distribution:list')


class LogListView(LoginRequiredMixin, ListView):
    model = MailingLog

    def get_queryset(self):
        user = self.request.user
        if user.is_staff or user.is_superuser:  # для работников и суперпользователя
            queryset = super().get_queryset()
        else:  # для остальных пользователей
            queryset = super().get_queryset().filter(owner=user)
        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['title'] = 'Список логов'

        context_data['all'] = context_data['object_list'].count()
        context_data['success'] = context_data['object_list'].filter(status=True).count()
        context_data['error'] = context_data['object_list'].filter(status=False).count()

        return context_data


class LogDetailView(LoginRequiredMixin, DetailView):
    model = MailingLog

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        log = self.get_object()
        context_data['title'] = f'log: {log.pk}'
        return context_data


class LogDeleteView(LoginRequiredMixin, DeleteView):
    model = MailingLog
    success_url = reverse_lazy('distribution:log_list')
    extra_context = {
        'title': 'Удалить лог',

distribution/templates/distribution/mailinglog_confirm_delete.html
{% extends 'users/base.html' %}

{% block content %}

<div class="container">
    <div class="card col-8">
        <div class="card-body">
            <h5 class="card-title">Хотите удалить Лог</h5>
            <p class="card-text mb-3">Дата попытки: {{ object.time }}</p>
            <p class="card-text mb-3">Статус: {{ object.status }}</p>
            <p class="card-text mb-3">Ответ сервера: {{ object.server_response }}</p>
            {% if user.is_staff %}
            <p class="card-text mb-3">Автор: {{ object.owner }}</p>
            {% endif %}
            <a href="{% url 'distribution:view' object.mailing.pk %}" type="button"
               class="btn btn-sm btn-outline-secondary">К рассылке</a>
        </div>
        <div class="card-footer">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <button type="submit" class="btn btn-lg btn-block btn btn-danger">Удалить</button>
                <a type="button" href="{% url 'distribution:log_list'%}"
                   class="btn btn-lg btn-block btn-outline-primary">Назад</a>
            </form>
        </div>
    </div>
</div>

{% endblock %}

distribution/templates/distribution/mailinglog_detail.html
{% extends 'users/base.html' %}

{% block content %}

<div class="container">
    <div class="card col-8">
        <div class="card-body">

            <p class="card-text mb-3">Дата попытки: {{ object.time }}</p>
            <p class="card-text mb-3">Статус: {{ object.status }}</p>
            <p class="card-text mb-3">Ответ сервера: {{ object.server_response }}</p>
            {% if user.is_staff %}
            <p class="card-text mb-3">Автор: {{ object.owner }}</p>
            {% endif %}

            <a href="{% url 'distribution:view' object.mailing.pk %}" type="button"
               class="btn btn-sm btn-outline-secondary">К рассылке</a>
        </div>
        <div class="card-footer">

            <a type="button" href="{% url 'distribution:log_list'%}"
               class="btn btn-lg btn-block btn-outline-primary">Назад</a>

        </div>
    </div>
</div>

{% endblock %}

distribution/templates/distribution/mailinglog_list.html
{% extends 'users/base.html' %}
{% load my_tags %}
{% block content %}

<div class="container col-8 mt-2 mb-5">
    <div class="card">
        <div class="card-header text-center">
            <h1>Статистика</h1>
        </div>
        <div class="card-body">
            <div class="row text-center ">
                <div class="col-12">
                    <table class="table">
                        <thead>
                        <tr>
                            <th><h4>Количество отправленных писем</h4></th>
                            <th><h4>Отправленно успешно</h4></th>
                            <th><h4>Количество ошибок</h4></th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td><h4>{{ all }}</h4></td>
                            <td><h4>{{ success }}</h4></td>
                            <td><h4>{{ error }}</h4></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container text-center">
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Дата попытки</th>
            <th scope="col">Статус</th>
            <th scope="col">Ответ сервиса</th>
            {% if user.is_staff %}
            <th scope="col">Владелец</th>
            {% endif %}
            <th scope="col">Действия</th>
        </tr>
        </thead>
        <tbody>

        {% for log in object_list %}

        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ log.time }}</td>
            <td>{{ log.status }}</td>
            <td>{{ log.server_response }}</td>
            {% if user.is_staff %}
            <td>{{ log.owner }}</td>
            {% endif %}
            <td>
                <div class="btn-group" role="group" aria-label="Basic outlined example">
                    <a href="{% url 'distribution:log_detail' log.pk %}" type="button"
                       class="btn btn-sm btn-outline-secondary">Детали</a>
                    <a href="{% url 'distribution:view' log.mailing.pk %}" type="button"
                       class="btn btn-sm btn-outline-secondary">К рассылке</a>
                    {% if not user|has_group:"manager" %}
                    <a href="{% url 'distribution:log_delete' log.pk %}" type="button"
                       class="btn btn-sm btn btn-danger">Delete</a>
                    {% endif %}
                </div>
            </td>
        </tr>

        {% endfor %}

        </tbody>
    </table>
</div>

{% endblock %}

distribution/templates/distribution/mailingsettings_confirm_delete.html
{% extends 'users/base.html' %}

{% block content %}

<div class="container">
    <div class="card col-8">
        <div class="card-body">

            <h5 class="card-title">Хотите удалить рассылку:</h5>
            <p class="card-title">Дата создания: {{ object.created_at }}</p>
            <p class="card-title">Начало рассылки: {{ object.start_time }}</p>
            <p class="card-title">Завершение рассылки: {{ object.end_time }}</p>
            <p class="card-title">Следующая рассылка: {{ object.next_send }}</p>
            <p class="card-title">Период рассылки: {{ object.periodicity }}</p>
            <p class="card-title">Статус: {{ object.status }}</p>
            <p class="card-title">Сообщение: {{ object.message.title|truncatechars:20 }}</p>
            <p class="card-title">Клиенты:
                {% for object in object.clients.all %}
                {{ object.email }},
                {% endfor %}</p>

        </div>
        <div class="card-footer">

            {% if request.user.is_staff %}
            <p class="card-text mb-3">Владелец: {{ object.owner }}</p>
            {% endif %}
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Delete</button>
                <a type="button" href="{% url 'distribution:list'%}"
                   class="btn btn-lg btn-block btn-outline-primary">return</a>
            </form>
        </div>
    </div>
</div>

{% endblock %}

distribution/templates/distribution/mailingsettings_detail.html
{% extends 'users/base.html' %}

{% block content %}

<div class="container">
    <div class="card col-8">
        <div class="card-body">

            <p class="card-title">Дата создания: {{ object.created_at }}</p>
            <p class="card-title">Начало рассылки: {{ object.start_time }}</p>
            <p class="card-title">Завершение рассылки: {{ object.end_time }}</p>
            <p class="card-title">Следующая рассылка: {{ object.next_send }}</p>
            <p class="card-title">Период рассылки: {{ object.periodicity }}</p>
            <p class="card-title">Статус: {{ object.status }}</p>
            <p class="card-title">Сообщение: {{ object.message.title|truncatechars:20 }}</p>
            <p class="card-title">Клиенты:
                {% for object in object.clients.all %}
                {{ object.email }},
                {% endfor %}
            </p>

        </div>
        <div class="card-footer">

            {% if request.user.is_staff %}
            <p class="card-text mb-3">Владелец: {{ object.owner }}</p>
            {% endif %}
            <a type="button" href="{% url 'distribution:list'%}"
               class="btn btn-lg btn-block btn-outline-primary">return</a>

        </div>
    </div>
</div>

{% endblock %}

distribution/templates/distribution/mailingsettings_form.html
{% extends "users/base.html" %}

{% block content %}

<div class="text-center container">
    <form method="post">
        <div class="card col-8">
            <div class="card-body">

                {% csrf_token %}
                {{ form.as_p }}

                <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                    {% if object %}
                    Изменить
                    {% else %}
                    Создать
                    {% endif %}
                </button>
                <a type="button" href="{% url 'distribution:list'%}"
               class="btn btn-lg btn-block btn-outline-primary">return</a>

            </div>
        </div>
    </form>
</div>

{% endblock %}

distribution/templates/distribution/mailingsettings_list.html
{% extends 'users/base.html' %}
{% load my_tags %}
{% block content %}

{% if not user|has_group:"manager" %}
<div class="text-center container">
    <a class="btn btn-primary" href="{% url 'distribution:create' %}" type="button">Добавить рассылку</a>
</div>
{% endif %}

<div class="container col-8 mt-2 mb-5">
    <div class="card">
        <div class="card-header text-center">
            <h1>Статистика</h1>
        </div>
        <div class="card-body">
            <div class="row text-center ">
                <div class="col-12">
                    <table class="table">
                        <thead>
                        <tr>
                            <th><h4>Количество рассылок</h4></th>
                            <th><h4>Количество активных рассылок</h4></th>
                            <th><h4>Количество завершенных рассылок</h4></th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td><h4>{{ all }}</h4></td>
                            <td><h4>{{ active }}</h4></td>
                            <td><h4>{{ completed }}</h4></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container text-center">
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Дата создания</th>
            <th scope="col">Начало рассылки</th>
            <th scope="col">Завершение рассылки</th>
            <th scope="col">Период рассылки</th>
            <th scope="col">Статус</th>
            <th scope="col">Активность</th>
            {% if request.user.is_staff %}
            <th scope="col">Владелец</th>
            {% endif %}
            <th scope="col">Действия</th>
        </tr>
        </thead>
        <tbody>

        {% for distribution in object_list %}

        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ distribution.created_at }}</td>
            <td>{{ distribution.start_time }}</td>
            <td>{{ distribution.end_time }}</td>
            <td>{{ distribution.periodicity }}</td>
            <td>{{ distribution.status }}</td>
            {% if request.user.is_staff %}
            {% if distribution.is_active %}
            <td>
                <a href="{% url 'distribution:toggle_active' distribution.pk %}" type="button"
                   class="btn btn-success">True</a>
            </td>
            {% else %}
            <td>
                <a href="{% url 'distribution:toggle_active' distribution.pk %}" type="button"
                   class="btn btn-danger">False</a>
            </td>
            {% endif %}
            <td>{{ distribution.owner }}</td>
            {% else %}
            <td>{{ distribution.is_active }}</td>
            {% endif %}
            <td>
                <div class="btn-group" role="group" aria-label="Basic outlined example">
                    <a href="{% url 'distribution:view' distribution.pk %}" type="button"
                       class="btn btn-sm btn-outline-secondary">View</a>
                    {% if not user|has_group:"manager" %}
                    <a href="{% url 'distribution:edit' distribution.pk %}" type="button"
                       class="btn btn-sm btn-outline-secondary">Edit</a>
                    <a href="{% url 'distribution:delete' distribution.pk %}" type="button"
                       class="btn btn-sm btn btn-danger">Delete</a>
                    {% endif %}
                </div>
            </td>
        </tr>

        {% endfor %}

        </tbody>
    </table>
</div>

{% endblock %}

distribution/templates/distribution/message_list.html
{% extends 'users/base.html' %}
{% load my_tags %}
{% block content %}

{% if not user|has_group:"manager" %}
<div class="text-center container">
    <a class="btn btn-primary" href="{% url 'distribution:message_create' %}" type="button">Добавить сообщение</a>
</div>
{% endif %}

<div class="container text-center">
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Заголовок</th>
            <th scope="col">Сообщение</th>
            {% if request.user.is_staff %}
            <th scope="col">Владелец</th>
            {% endif %}
            <th scope="col">Действие</th>
        </tr>
        </thead>
        <tbody>

        {% for message in object_list %}

        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ message.title|truncatechars:25 }}</td>
            <td>{{ message.text|truncatechars:25 }}</td>
            {% if request.user.is_staff %}
            <td>{{ message.owner }}</td>
            {% endif %}
            <td>
                <div class="btn-group" role="group" aria-label="Basic outlined example">
                    <a href="{% url 'distribution:message_view' message.pk %}" type="button"
                       class="btn btn-sm btn-outline-secondary">View</a>
                    {% if not user|has_group:"manager" %}
                    <a href="{% url 'distribution:message_edit' message.pk %}" type="button"
                       class="btn btn-sm btn-outline-secondary">Edit</a>
                    <a href="{% url 'distribution:message_delete' message.pk %}" type="button"
                       class="btn btn-sm btn-outline-secondary">Delete</a>
                    {% endif %}
                </div>
            </td>
        </tr>

        {% endfor %}

        </tbody>
    </table>
</div>

{% endblock %}